### ISSUE TITLE
Feature: Prevent clear passwords to be shown without security prompt

### ISSUE THREAD

**Issue by hr87** [nextcloud/passman-webextension#139]
It is possible to easily extract clear text passwords from this extension if the vault is unlocked. There should be a way to prevent the copy or clear text presentation of the password without an additional password prompt. This would prevent that someone with physical access to the computer can extract passwords easily.

The wanted behavior can be seen with the Firefox password manager, if a master password is set. The password can only be copied or shown if the master password is entered again, even if the password manager is already unlocked. 

### Steps to reproduce
1. Unlock vault
2. Search for a password and edit entry
3. Click on clear text next to password

### Expected behaviour
The extension should ask for a password to present any clear text passwords

### Actual behaviour
The extension presents clear text passwords without security prompt

### Configuration
**Operating system**:  Ubuntu 17.04

**Browser**: Firefox 54.0

**Extensions that might cause interference**: None

**Passman version**: 2.1.2

**Extension version**: 2.0.0

**Nextcloud version**: 12.0

**Comment by brantje** [comment]
You can lock the extension if you're afraid if somebody is going to copy your passwords.
I'm always nearby my PC if someone is using it. They can fill in the username and password fields, but if i see them going to the extension and search, well i will stop them of course.
Your passwords are not locally stored, and there is no way for extensions to gain access to the passwords.

**Comment by dardelet** [comment]
Agreed. If you want that behavior you should ask the extension to remember your master password, so that you have to unlock it each time you want to use it

**Comment by hr87** [comment]
In my opinion one can't be too careful, if a lot of login credential are involved, so this additional layer of security would be good. The behavior would be, that one unlocks the extension once and it fills out the forms without any possibility to extract the password without additional password prompt. As I said, that is the default Firefox behavior.

I know that I can lock the extension. However, one has to unlock the vault before visiting a website. The extension does not recognize the password prompt, if the website is already loaded at the time, when the extension gets unlocked.

An even better behavior would be, if there was a setting to automatically lock the vault after each time it is used. The extension then should prompt the master password every time it recognized a login page, fill out the form and lock the vault again. That would be the best security.

These are just suggestions, which in my opinion, can make the difference between a good and an excellent extension. Anyway, thanks for the good work so far.

**Comment by OS3DrNick** [comment]
I currently don't use the extension yet.
But for me it would be so that I would have 1 big master vault password and I don't want to use that every time I visit a site.
Locking the vault is an option when you walk away of your computer. But best is locking your computer with a password protected screensaver.
That way no one would get in when you are away from your computer. And when they know that password. Well then you will need to add your own additional actions to prevent access.

**Comment by maestroi** [comment]
So i tried firefox to see how there "vault" works. i found the following,, if you enable the masterpassword and you want to see the password from one of the credentials, you need to fill in the master password again.

But it Does NOT do it when password is inserted inside a form, so this is not really more secure, because you can change properties of a password input field to text by changing the source and there is your plain-text password.

My point is this feature will not add real security so seems a bit extensive.
See:
![2017-07-26_08-42-35](https://user-images.githubusercontent.com/16004566/28607957-90650d6e-71de-11e7-910c-e472dd6bde9e.gif)

**Comment by brantje** [comment]
Closing, this won't be implemented
