### ISSUE TITLE
Unlocking doesn't seem to work

### ISSUE THREAD

**Issue by oparoz** [nextcloud/passman-webextension#5]
### Steps to reproduce
1. Install
2. Connect
3. Set master password
1. Click on lock icon
1. Access Passman
1. Type master password

### Expected behaviour

I should have access to my vault

### Actual behaviour

I'm told my password is invalid

### Configuration
**Operating system**:   Win10

   
**Browser**:   Chrome
   
   
**Extensions that might cause interference**:   No idea
   
   
**Passman version**:    1.0.0
       
       
**Nextcloud version**: 11.0.1
   
#### Browser log
<details>
<summary>Browser log</summary>
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by brantje** [comment]
Can you open the developer

**Comment by brantje** [comment]
Can you open the developer tools? Right click on the extension and then click inspect.
Are there any errors in the console?

**Comment by oparoz** [comment]
No JS errors

**Comment by brantje** [comment]
Can you reload the extension and see if it still happens?

**Comment by oparoz** [comment]
I uninstalled and re-installed. Same problem.

**Comment by rogerdk** [comment]
+1

**Comment by kbaegis** [comment]
Did a little investigation. I use local dns and host nextcloud behind a rproxy, so the path is {https://<host>/cloud/}. This doesn't work, complaining "destination doesn't exist". Encoding an IP instead worked, but my internal CA was ignored. It doesn't appear to be pulling these from my system, and so https is ignored. https://<ip>:443/cloud/ was recognized, and starts talking to /heartbeat, but again the session is ignored due to certs.

**Comment by brantje** [comment]
We don't use any heartbeat from NC. Does the issue still exist in the master branch?

**Comment by kbaegis** [comment]
Yes, temporary plugin from master. I see a 200 come back from /cloud/[can't remember]/heartbeat

**Comment by garan2314** [comment]
Facing the same issue here, tried reinstalling, different master passwords, all to no avail.
