### ISSUE TITLE
Import from Firefox' password manager

### ISSUE THREAD

**Issue by rugk** [nextcloud/passman-webextension#82]
It would be nice if one could import passwords from Firefox' internal password manager. Either only when this extension is installed (with one click or so) or in the web interface with some manual steps, which are reasonable to be done by a "usual user". (So not: "Go into your profile dir, open the database file there, extract the passwords using your master password with a special developer program.")

**Comment by brantje** [comment]
Impossible due security restrictions.

**Comment by brantje** [comment]
Same for chrome btw

**Comment by rugk** [comment]
Also not with manual intervention? Like user doing Ctrl+A and copying all the passwords?

**Comment by brantje** [comment]
The user has to paste javascripts in to the console to export passwords. Which is not user friendly imo.
Older firefox extensions do have access to the password manager. More info: https://developer.mozilla.org/en-US/Add-ons/SDK/High-Level_APIs/passwords

But, those extensions will be deprecated by the end of this year. Then firefox only uses webextensions like chrome does.

**Comment by rugk** [comment]
Thanks for your answer. At least for experienced users, could you offer such a JS in this issue (or in a GitHub gist or so), which create a JSON output one can important in Passman?

**Comment by brantje** [comment]
Chrome: https://superuser.com/a/1215715
Firefox https://addons.mozilla.org/en-US/firefox/addon/password-exporter/ -> Use CSV and then import using the generic csv importer.

**Comment by rugk** [comment]
Thanks for the links, however, the Firefox add-on is not only a JS method, so when only WebExtensions will be supported it won't work and secondly it returns an XML file and not a JSON one… :cry:

**Comment by jzielke84** [comment]
I just tried out this extensions and I'd love to use it instead of the built in passwort manager of firefox.
But not being able to import passwords makes this extension worthless unless you start creating passwords from scratch for every website you ever might have saved a password for or you have to visit all of them and make the extension catch the password while logging in, which also is a serious pita. I know it's not the developers fault because of the webextension stuff, but I think there should be put more pressure on the mozilla developers also by the extension coders for not implementing things like they should be. Password managers aren't rocket science nor something completely new.

**Comment by brantje** [comment]
If chrome / Mozilla doesn't allow access to passwords there is nothing we can do.

**Comment by rugk** [comment]
I think you can follow https://bugzilla.mozilla.org/show_bug.cgi?id=1359182 for the discussion and comment there, if you want.
